import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Conditions d’utilisation · La Sportive" };

export default function TermsPage() {
  return <LegalPage title="Conditions d’utilisation" introduction="Ces conditions encadrent l’utilisation de La Sportive par les membres du bureau de l’association. L’application est exclusivement destinée à la gestion interne et ne propose aucun espace adhérent.">
    <section><h2>1. Objet de l’application</h2><p>La Sportive accompagne le suivi des adhésions issues de HelloAsso : vérification des dossiers, préparation des licences, suivi comptable et des réductions, consultation des autorisations, gestion des justificatifs et relances. Les utilisateurs doivent prendre connaissance de ces conditions avant d’utiliser l’outil.</p></section>
    <section><h2>2. Personnes autorisées et accès</h2><p>Seuls les membres du bureau autorisés par l’association peuvent utiliser l’application. La qualité d’adhérent, de parent, d’entraîneur ou de bénévole ne donne pas de droit d’accès.</p><p>L’accès s’effectue au moyen du compte partagé de l’association. Les identifiants doivent rester confidentiels et ne doivent être transmis qu’aux membres du bureau habilités. Chaque utilisateur doit se déconnecter à la fin de son utilisation et protéger le poste employé.</p><p>Lorsqu’un membre quitte le bureau ou perd son habilitation, il doit cesser immédiatement d’utiliser l’outil. Le bureau organise le renouvellement des identifiants partagés et, avec l’administrateur, les mesures nécessaires concernant les sessions encore ouvertes.</p></section>
    <section><h2>3. Utilisation dans le cadre des missions du bureau</h2><p>L’utilisateur consulte et modifie uniquement les informations nécessaires à ses missions associatives. Il vérifie les destinataires avant toute relance, la pertinence des pièces importées et l’exactitude des corrections ou validations.</p><p>Il est interdit d’utiliser les données à des fins personnelles, commerciales ou étrangères à l’association, de partager des dossiers avec des personnes non habilitées, de contourner les protections de l’outil ou d’y déposer des contenus malveillants.</p></section>
    <section><h2>4. Confidentialité des dossiers</h2><p>Les informations relatives aux adhérents, aux mineurs, aux familles et aux contacts d’urgence sont confidentielles. Les exports, captures d’écran, impressions et documents téléchargés sont soumis aux mêmes règles que les données consultées dans l’application.</p><p>Ils doivent être limités au besoin de la mission, conservés dans les espaces autorisés et supprimés lorsqu’ils ne sont plus nécessaires, sous réserve des obligations de conservation. L’obligation de confidentialité demeure après la fin du mandat.</p><p>Les traitements de données sont décrits dans les <Link href="/confidentialite">règles de confidentialité</Link>.</p></section>
    <section><h2>5. Vérification des informations et services tiers</h2><p>HelloAsso constitue la source des inscriptions ; les corrections effectuées dans La Sportive sont suivies séparément. Une modification dans l’application ne doit pas être considérée comme une modification automatiquement reportée dans HelloAsso.</p><p>Les statuts et contrôles facilitent le travail du bureau. Ils ne remplacent pas la vérification des pièces ni la décision des organismes compétents pour les licences ou les aides. Avant une transmission ou une validation, l’utilisateur contrôle les informations utiles.</p><p>Les fonctions connectées à HelloAsso, Google Drive et Brevo dépendent de leur configuration et de la disponibilité de ces services. L’association doit utiliser des comptes et des autorisations adaptés à ses besoins.</p></section>
    <section><h2>6. Disponibilité, incidents et responsabilité</h2><p>L’application peut être interrompue pour maintenance, mise à jour ou incident technique. La disponibilité permanente et l’absence d’erreurs ne sont pas garanties. En cas d’anomalie, l’utilisateur prévient l’administrateur et évite de répéter une opération dont le résultat est incertain, notamment un envoi de relance.</p><p>L’association organise les habilitations, la conservation des données et les procédures de sauvegarde. Chaque utilisateur répond de ses usages dans le cadre des règles applicables et signale sans délai toute erreur, divulgation ou suspicion d’accès non autorisé.</p></section>
    <section><h2>7. Fin d’accès et évolution des conditions</h2><p>Le bureau peut retirer une habilitation en cas de fin de mission, d’usage inapproprié ou de risque pour les données. L’utilisateur restitue les documents associatifs et supprime les copies qu’il n’est plus autorisé à conserver.</p><p>Ces conditions peuvent évoluer avec les fonctionnalités et l’organisation de l’association. La version en vigueur est accessible sur cette page ; le bureau informe les utilisateurs des modifications importantes.</p></section>
    <section><h2>8. Contact et droit applicable</h2><p>Pour toute question sur l’utilisation de La Sportive, contactez l’administrateur ou la présidence de l’association par les canaux habituels du bureau. Ces conditions sont soumises au droit français. Toute difficulté doit d’abord être signalée au bureau afin de rechercher une résolution amiable, sans priver les personnes de leurs recours légaux.</p></section>
  </LegalPage>;
}
